import fs from 'fs'
import path from 'path'

const OUTPUT_DIR = './outputs'
const DOCUMENTS_DIR = './documents'
const KNOWLEDGE_DIR = './knowledge'

console.log('📁 File Module initialized')
console.log(`   Output: ${OUTPUT_DIR}`)
console.log(`   Documents: ${DOCUMENTS_DIR}`)
console.log(`   Knowledge: ${KNOWLEDGE_DIR}\n`)

/**
 * CREATE FILE
 */
export async function createFile(filename, content, category = 'documents') {
  try {
    // Ensure category folder exists
    const categoryDir = `${OUTPUT_DIR}/${category}`
    fs.mkdirSync(categoryDir, { recursive: true })

    const filepath = `${categoryDir}/${filename}`

    // Write file
    fs.writeFileSync(filepath, content, 'utf8')

    const size = Buffer.byteLength(content, 'utf8')
    console.log(`   ✅ Created: ${filepath} (${size} bytes)`)

    return {
      success: true,
      path: filepath,
      filename: filename,
      size: size,
      category: category
    }

  } catch (error) {
    console.error(`   ❌ File creation error: ${error.message}`)
    return { success: false, error: error.message }
  }
}

/**
 * CREATE JSON FILE
 */
export async function createJSON(filename, data) {
  try {
    const content = JSON.stringify(data, null, 2)
    return createFile(filename || 'data.json', content, 'data')
  } catch (error) {
    console.error(`   ❌ JSON creation error: ${error.message}`)
    return { success: false, error: error.message }
  }
}

/**
 * CREATE MARKDOWN FILE
 */
export async function createMarkdown(filename, content) {
  try {
    const mdContent = content || '# Document\n\nNo content provided.'
    return createFile(filename || 'document.md', mdContent, 'documents')
  } catch (error) {
    console.error(`   ❌ Markdown creation error: ${error.message}`)
    return { success: false, error: error.message }
  }
}

/**
 * CREATE PDF (Basic text to PDF)
 */
export async function createPDF(filename, content) {
  try {
    // For now, save as text representation
    // In production, use a PDF library like pdfkit
    const pdfContent = `ORION DOCUMENT
================

Created: ${new Date().toISOString()}

${content}
`
    return createFile(filename || 'document.pdf', pdfContent, 'documents')
  } catch (error) {
    console.error(`   ❌ PDF creation error: ${error.message}`)
    return { success: false, error: error.message }
  }
}

/**
 * CREATE HTML FILE
 */
export async function createHTML(filename, htmlContent) {
  try {
    const fullHTML = `<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ORION - ${filename}</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            max-width: 800px;
            margin: 0 auto;
            padding: 20px;
            background: #f5f5f5;
        }
        .container {
            background: white;
            border-radius: 8px;
            padding: 30px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        h1 { color: #d62828; }
        h2 { color: #f77f00; }
        a { color: #d62828; }
    </style>
</head>
<body>
    <div class="container">
        ${htmlContent}
    </div>
</body>
</html>`

    return createFile(filename || 'document.html', fullHTML, 'documents')
  } catch (error) {
    console.error(`   ❌ HTML creation error: ${error.message}`)
    return { success: false, error: error.message }
  }
}

/**
 * CREATE CODE FILE
 */
export async function createCode(filename, code, language = 'javascript') {
  try {
    const header = `// ORION Auto-Generated Code
// Language: ${language}
// Created: ${new Date().toISOString()}
// DO NOT EDIT DIRECTLY - Generated by Mintaka

`
    const fullCode = header + code
    return createFile(filename || `script.${language === 'python' ? 'py' : 'js'}`, fullCode, 'code')
  } catch (error) {
    console.error(`   ❌ Code creation error: ${error.message}`)
    return { success: false, error: error.message }
  }
}

/**
 * READ FILE
 */
export async function readFile(filepath) {
  try {
    // Only allow reading from allowed directories
    const allowedDirs = [OUTPUT_DIR, DOCUMENTS_DIR, KNOWLEDGE_DIR]
    const resolved = path.resolve(filepath)

    const isAllowed = allowedDirs.some(dir => 
      resolved.startsWith(path.resolve(dir))
    )

    if (!isAllowed) {
      throw new Error(`Access denied: ${filepath}`)
    }

    if (!fs.existsSync(filepath)) {
      throw new Error(`File not found: ${filepath}`)
    }

    const content = fs.readFileSync(filepath, 'utf8')
    console.log(`   ✅ Read: ${filepath} (${content.length} chars)`)

    return {
      success: true,
      path: filepath,
      content: content,
      size: Buffer.byteLength(content, 'utf8')
    }

  } catch (error) {
    console.error(`   ❌ Read error: ${error.message}`)
    return { success: false, error: error.message }
  }
}

/**
 * LIST FILES IN DIRECTORY
 */
export async function listFiles(directory = OUTPUT_DIR) {
  try {
    if (!fs.existsSync(directory)) {
      return { success: false, error: `Directory not found: ${directory}` }
    }

    const files = fs.readdirSync(directory, { recursive: true })
    const fileList = files.map(f => {
      const fullPath = `${directory}/${f}`
      const stat = fs.statSync(fullPath)
      return {
        name: f,
        size: stat.size,
        modified: stat.mtime.toISOString(),
        isDir: stat.isDirectory()
      }
    })

    console.log(`   ✅ Listed ${fileList.length} items in ${directory}`)

    return {
      success: true,
      directory: directory,
      count: fileList.length,
      files: fileList
    }

  } catch (error) {
    console.error(`   ❌ List error: ${error.message}`)
    return { success: false, error: error.message }
  }
}

/**
 * DELETE FILE
 */
export async function deleteFile(filepath, confirm = false) {
  try {
    if (!confirm) {
      return {
        success: false,
        error: 'Deletion requires confirmation',
        path: filepath
      }
    }

    if (!fs.existsSync(filepath)) {
      throw new Error(`File not found: ${filepath}`)
    }

    fs.unlinkSync(filepath)
    console.log(`   ✅ Deleted: ${filepath}`)

    return {
      success: true,
      path: filepath,
      deleted: true
    }

  } catch (error) {
    console.error(`   ❌ Delete error: ${error.message}`)
    return { success: false, error: error.message }
  }
}

/**
 * ARCHIVE OLD FILES
 */
export async function archiveOldFiles(daysOld = 90) {
  try {
    const archiveDir = `${OUTPUT_DIR}/archive`
    fs.mkdirSync(archiveDir, { recursive: true })

    const now = Date.now()
    const cutoff = daysOld * 24 * 60 * 60 * 1000

    let archived = 0

    const files = fs.readdirSync(OUTPUT_DIR, { recursive: true })
    for (const file of files) {
      const filepath = `${OUTPUT_DIR}/${file}`
      const stat = fs.statSync(filepath)

      if (now - stat.mtime.getTime() > cutoff && !stat.isDirectory()) {
        const destPath = `${archiveDir}/${file}`
        fs.mkdirSync(path.dirname(destPath), { recursive: true })
        fs.renameSync(filepath, destPath)
        archived++
      }
    }

    console.log(`   ✅ Archived ${archived} old files`)
    return { success: true, archived }

  } catch (error) {
    console.error(`   ❌ Archive error: ${error.message}`)
    return { success: false, error: error.message }
  }
}

/**
 * GET STORAGE STATS
 */
export async function getStorageStats() {
  try {
    let totalSize = 0
    let fileCount = 0

    const walk = (dir) => {
      const files = fs.readdirSync(dir)
      files.forEach(file => {
        const filepath = `${dir}/${file}`
        const stat = fs.statSync(filepath)
        if (stat.isDirectory()) {
          walk(filepath)
        } else {
          totalSize += stat.size
          fileCount++
        }
      })
    }

    walk(OUTPUT_DIR)

    return {
      success: true,
      totalFiles: fileCount,
      totalSize: totalSize,
      totalSizeMB: (totalSize / 1024 / 1024).toFixed(2),
      directory: OUTPUT_DIR
    }

  } catch (error) {
    console.error(`   ❌ Stats error: ${error.message}`)
    return { success: false, error: error.message }
  }
}

/**
 * ENSURE DIRECTORIES EXIST
 */
export function initializeFolders() {
  const folders = [
    OUTPUT_DIR,
    `${OUTPUT_DIR}/proposals`,
    `${OUTPUT_DIR}/documents`,
    `${OUTPUT_DIR}/code`,
    `${OUTPUT_DIR}/data`,
    `${OUTPUT_DIR}/archive`,
    DOCUMENTS_DIR,
    KNOWLEDGE_DIR
  ]

  folders.forEach(folder => {
    fs.mkdirSync(folder, { recursive: true })
  })

  console.log('✅ All folders initialized')
}

export default {
  createFile,
  createJSON,
  createMarkdown,
  createPDF,
  createHTML,
  createCode,
  readFile,
  listFiles,
  deleteFile,
  archiveOldFiles,
  getStorageStats,
  initializeFolders
}
